import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Copyright Notice",
  description: "Copyright Notice for Andy'K Music Lab and all associated content.",
  alternates: { canonical: "https://lab.djandykofficial.com/copyright" },
};

export default function Copyright() {
  return (
    <div className="tool-page-bg min-h-screen py-16 px-4">
      <div className="max-w-3xl mx-auto">
        <div className="glass-card p-8 md:p-12">
          <p className="font-mono text-xs text-[#63B39A] tracking-widest uppercase mb-4">Legal</p>
          <h1 className="text-3xl font-bold mb-2">Copyright Notice</h1>
          <p className="text-sm font-mono opacity-40 mb-10">Last updated: 1 May 2026</p>

          <div className="prose-legal">

            <div className="copyright-notice-block text-center py-8 mb-8" style={{ borderTop: "1px solid rgba(99,179,154,0.15)", borderBottom: "1px solid rgba(99,179,154,0.15)" }}>
              <p className="text-2xl font-bold tracking-wide mb-2">℗ &amp; © 2026</p>
              <p className="text-xl font-mono text-[#63B39A] tracking-widest uppercase">ANDY&apos;K GROUP INTERNATIONAL LTD</p>
              <p className="text-sm opacity-40 mt-2">All Rights Reserved</p>
            </div>

            <h2>Ownership</h2>
            <p>
              The Andy&apos;K Music Lab service, including but not limited to its software, design, user interface,
              algorithms, branding, trademarks, trade names, logos, text, graphics, and all other content
              (&ldquo;Content&rdquo;), is the exclusive property of <strong>ANDY&apos;K GROUP INTERNATIONAL LTD</strong>
              (Company No. 16453500) and is protected by copyright, trademark, and other intellectual property
              laws of the United Kingdom and international treaties.
            </p>

            <h2>Music &amp; Sound Recordings</h2>
            <p>
              All music, sound recordings, mixes, and audio releases associated with the DJ Andy&apos;K brand are:
            </p>
            <p className="font-mono text-[#63B39A] text-center py-2">
              ℗ &amp; © ANDY&apos;K GROUP INTERNATIONAL LTD. All Rights Reserved.
            </p>
            <p>
              Unauthorised copying, reproduction, hiring, lending, public performance, diffusion, broadcasting,
              or distribution of any sound recording is prohibited.
            </p>

            <h2>Software</h2>
            <p>
              The software powering Andy&apos;K Music Lab, including all source code, algorithms, and associated
              documentation, is copyright © ANDY&apos;K GROUP INTERNATIONAL LTD. You may not reproduce, distribute,
              modify, create derivative works of, publicly display, or otherwise exploit the software without
              prior written permission.
            </p>

            <h2>Your Content</h2>
            <p>
              Audio files and other content you upload to the Service remain your property. By using the Service,
              you grant us no rights over your content beyond what is necessary to provide the Service to you.
              Your audio files are processed locally in your browser and are never transmitted to our servers.
            </p>

            <h2>Permitted Use</h2>
            <p>You may:</p>
            <ul>
              <li>Use the Service for its intended purpose (audio processing and planning)</li>
              <li>Share links to the Service</li>
              <li>Export results generated by the Service for your own use</li>
            </ul>
            <p>You may not:</p>
            <ul>
              <li>Copy, reproduce, or redistribute the Service&apos;s software or design</li>
              <li>Use our trademarks or logos without written permission</li>
              <li>Create derivative works based on our Content</li>
            </ul>

            <h2>Reporting Infringement</h2>
            <p>
              If you believe that any content on the Service infringes your copyright, please notify us at{" "}
              <a href="mailto:info@djandykofficial.com">info@djandykofficial.com</a> with details of the alleged
              infringement.
            </p>

            <h2>Contact</h2>
            <p>
              ANDY&apos;K GROUP INTERNATIONAL LTD<br />
              86-90 Paul Street, London, EC2A 4NE<br />
              <a href="mailto:info@djandykofficial.com">info@djandykofficial.com</a>
            </p>
          </div>
        </div>
      </div>
    </div>
  );
}
